name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [20]
    
    steps:
      - name: Checkout Node
        uses: actions/checkout@v4
    
      - name: Setup Node
        uses: actions/setup-node@v4   
        with: 
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint  

      - name: run test
        run: npm run test    

      - name: Build Docker image
        run: docker build -t my-app .

      - name: run container
        run: docker run -d -p 3001:3001 my-app
      
      - name: checkout container
        run: curl http://localhost:3001